ALL_WORDS = [
    ["ABADDON", "AXE"],
    ["BREACH" ,"BRIMSTONE", "REYNA", "JETT", "PHOENIX", "SKYE", "NEON", "KILLJOY"],
    ["PYTHON", "JAVASCRIPT", "PHP", "PASCAL"],
    ["MOTHERBOARD", "KEYBOARD", "MOUSE", "MONITOR", "SYSTEMUNIT", "VIDEOCARD", "PROCESSOR", "HARDDRIVE", "RAM", "FANS", "HEADPHONES", "SSD"],
    ["RAZER", "LOGITECH", "STEELSERIES"],
    ["MCDONALDS", "JOLLIBEE", "KFC"]
]